# Before : 
# before(:all) {     }
# After :
# 
#
[[rules]]
name = "remove_empty_rspec_blocks"
groups = ["block_removal"]
query = """
(
(call
  method: (identifier) @method
  (argument_list (simple_symbol) @args)
  [
    (block
  	  !body
    )
    (do_block
  	  !body
    )
  ]
)@call
(#match? @method "(before|after)")
(#match? @args "(:suite|:all|:context|:each|:example)")
)
"""
replace = ""
replace_node = "call"

# Before 
#  context 'empty context block' do
#
#  end
# After 
#  


[[rules]]
name = "remove_empty_context"
groups = ["block_removal"]
query = """
(call
    method: (identifier) @method
    arguments: (argument_list
        (string) @description)
    block: (do_block
        !body)
    (#eq? @method "context")
) @to_remove
"""
replace_node = "to_remove"
replace = ""